version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - redis
    volumes:
      - ../backend:/chat

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"